### ISSUE TITLE
Don't Mix YAML and INI Syntax

### ISSUE THREAD

**Issue by opticyclic** [corda/corda-ansible#12]
Throughout this module and examples you are mixing YAML and INI syntax.
e.g.

    - name: Create user
      user: name={{ corda_user }} state=present groups={{ corda_user }}

Instead of:

    - name: Create user
      user: 
        name: "{{ corda_user }}" 
        state: present 
        groups: "{{ corda_user }}"

**Comment by benabineri** [comment]
Hi opticyclic,

Thanks for your feedback. Although you are right that we should probably stick to one format or the other, it does not do any harm to mix them and in fact some people recommend using the shorthand syntax for simple tasks and the longer syntax for more complex tasks, for example: https://www.jeffgeerling.com/blog/yaml-best-practices-ansible-playbooks-tasks

That said, this repo could definitely do with a tidy up. If you wanted to raise one, a PR would be gratefully received.

Ben

**Comment by wawrzek** [comment]
We've started to fix it. My recent branch should be merged soon and it addresses your comment. Maybe examples won't be consistent, but examples requires more work, so it's going to be updated later.
